namespace SunamoWinStd._public.SunamoEnums.Enums;

public enum Browsers : byte
{
    Chrome = 1,
    Firefox = 2,
    EdgeBeta = 3,
    Opera = 4,
    Vivaldi = 5,
    Slimjet = 6,
    WaterFox = 7,
    OperaGX = 8,
    ChromeCanary = 9,
    Tor = 10,
    Bravebrowser = 11,
    ChromeBeta = 12,
    EdgeDev = 13,
    EdgeCanary = 14,
    ChromeDev = 15,
    Min = 17,
    Basilisk = 18,
    NawerWhale = 19,
    KMeleon = 20,
    PaleMoon = 21,
    LibreWolf = 22,
    ChromeStable = 23,
    Arc = 24,
    Zen = 25,
    AvastBrowser = 26,
    Comodo = 27,
    Mullvad = 28,
    Floorp = 29,
    Sidekick = 30,
    Midori = 31,
    Comet = 32,
    EdgeStable = 254,
    None = 255
}
